services:
  redis:
    image: redis:7-alpine
    container_name: i6-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --save 60 1 --loglevel warning

  redis-http:
    image: hiett/serverless-redis-http:latest
    container_name: i6-redis-http
    ports:
      - "8079:80"
    environment:
      SRH_MODE: env
      SRH_TOKEN: local-dev-token
      SRH_CONNECTION_STRING: "redis://redis:6379"
    depends_on:
      - redis

volumes:
  redis-data:
